[project]
name = "mcp-local-rag"
version = "0.1.0"
description = "MCP \"server\" that locally performs a RAG search on your input query."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
 "aiohttp>=3.11.13",
 "beautifulsoup4>=4.13.3",
 "duckduckgo-search>=8.0.2",
 "mcp[cli]>=1.3.0",
 "mediapipe>=0.10.21",
 "requests>=2.32.3",
]
[[project.authors]]
name = "Nikhil Kapila"
email = "info@nkapila.me"

[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project.scripts]
mcp-local-rag = "mcp_local_rag.main:mcp.run"

[tool.setuptools.package-data]
mcp_local_rag = ["embedder/embedder.tflite"]

[tool.hatch.build.targets.wheel]
packages = ["src/mcp_local_rag"]
